Add the InfluxDB Timestream connector
awslabs/amazon-timestream-tools pull request #201
Opened 2024-11-01 20:22 UTC by trevorbonas

*Issue #, if available:*

N/A.

*Description of changes:*

The InfluxDB Timestream connector has been added.

The InfluxDB Timestream connector is a Rust application that receives, translates, and ingests line protocol data into Timestream for LiveAnalytics. The connector is intended to be deployed as part of a CloudFormation stack as a Lambda function, but can also be used as a library or run locally as a Lambda function.

The connector includes the following components:
- A README with documentation for how the connector translates line protocol data to Timestream records, a guide for using the connector, and documentation for different configuration options.
- A SAM template that deploys a REST API Gateway, using either synchronous or asynchronous deployment, and the connector as a Lambda function.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-03-09 04:25 UTC, pdhamoth requested changes
Thanks for adding comprehensive test cases

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +                "arn:aws:apigateway:{region}::/tags/*"
Can we make this scoped to the resource name pattern, similar to the other policies

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +- Reduce the amount of memory the connector uses as a Lambda function. The default, and smallest possible value, is 128 MB.
We have recommended to batch up to 20k points in each request, can we also add ideal lambda memory config on such workloads

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/docs/adr/require-line-protocol-tags.md
> +All components of a line protocol point are required except for tags.
nit: tags are required ?

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +use timestream_utils::*;
Can we avoid glob import `*`  ? use alias or import only specific methods as needed

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +    let line_protocol = str::from_utf8(body).unwrap();
nit: can we gracefully handle errors with logs and not just rely on panic to help customer identify the error if it's related to the payload format

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/line_protocol_parser.rs
> +    }
We parse through all the lines in the payload. Can we maintain some state to track datapoints with same tags, possibly we could use common attributes on write batches with same tags in the downstream  and save write cost.
Also, for `multi-table-multi-measure`, if measure name will be constant, can we add that to common attribute as well ?

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/records_builder.rs
> +    }
we are loading these static env variables multiple times. Can we organize all the env variable loading to a util and use `OnceCell` and just load all of them once and use them across

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +                        .await;
Can we optimize to maintain a local table cache once a table is created to avoid network calls as we could potentially create 1000s of tables for `multi_table_multi_measures`

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +    }
How do we help differentiate between a `retryable` v/s `non-retryable` ?
Also, can we add clarity on the format of DLQ messages between different error types (`CRUD / Write` , `retryable v/s non-retryables`) and how they can be deserialized from the queue and attempted for retries

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/tests/integration_test.rs
> +                        error.raw_response()
nit: can we use error! ?

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +            thread::sleep(time::Duration::from_secs(TIMESTREAM_API_WAIT_SECONDS));
we still have concurrency of `16` threads and could potentially hit throttling errors leading to wasted work for the failed tables as default CRUD TPS is `1`
Can we add some jitters with backoff to retry

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +                        .await;
nit: can we add logs for table and database creation failures

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +
nit: extra line

2025-03-09 04:25 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/src/timestream_utils.rs
> +            info!("SdkError: {:?}", error.raw_response().unwrap());
nit: error!

2025-03-10 16:38 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/docs/adr/require-line-protocol-tags.md
> +All components of a line protocol point are required except for tags.
Line protocol [does not require tags](https://docs.influxdata.com/influxdb/v2/reference/syntax/line-protocol/#tag-set).

The InfluxDB Timestream, however, connector requires tags in line protocol. This was a design decision explained in this document.

2025-03-10 16:46 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +- Reduce the amount of memory the connector uses as a Lambda function. The default, and smallest possible value, is 128 MB.
Are 20k points recommended for ingesting to Timestream for InfluxDB or to Timestream for LiveAnalytics? If it is the recommended batch size for Timestream for InfluxDB, is this batch size still relevant when ingesting to Timestream for LiveAnalytics?

Timestream for LiveAnalytics can only handle 100 records in a batch. This connector will split up batches and ingest a 100 at a time to Timestream for LiveAnalytics in parallel.

2025-03-10 17:10 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +use timestream_utils::*;
I have removed all glob imports and now only import necessary specific methods.

2025-03-10 17:35 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +    let line_protocol = str::from_utf8(body).unwrap();
I have added error handling for this. Users will get an error log and a returned error.

2025-03-10 23:01 UTC, pdhamoth commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +- Reduce the amount of memory the connector uses as a Lambda function. The default, and smallest possible value, is 128 MB.
Just want to make it a bit clear, neither referring to influx or LA batch for 20k points. Referring to this statement in line number 652, regarding the batching for this connector API and lambda handler

> 5,000-20,000 line protocol points in each request is ideal.

comment, is to get clarity on what should be the ideal lambda memory for a stable workload to this API and can we recommend

2025-03-11 16:41 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +- Reduce the amount of memory the connector uses as a Lambda function. The default, and smallest possible value, is 128 MB.
I see. I will updated the sample application to use 20k points and make a note of the recommended amount of memory for that batch size.

2025-03-12 23:03 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/tests/integration_test.rs
> +                        error.raw_response()
These calls and other prints in helper functions can be changed to `error!` or `info!`. From my understanding, the actual integration tests don't support logging without initializing the logger at the start of every test.

2025-03-18 23:13 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/tests/integration_test.rs
> +                        error.raw_response()
I have confirmed that logs for this entire file does not work. To show any output with `cargo test -- --nocapture` `println!` must be used instead, as it currently is.

2025-03-24 07:31 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +                "arn:aws:apigateway:{region}::/tags/*"
Unfortunately not. REST API ARNs use the following format: `arn:partition:apigateway:region::/restapis/api-id`. [Link (under `RestApi`)](https://docs.aws.amazon.com/apigateway/latest/developerguide/arn-format-reference.html#apigateway-v1-arns). The `api-id` is random and is not related to the REST API gateway's name pattern.

2025-03-29 01:00 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/README.md
> +- Reduce the amount of memory the connector uses as a Lambda function. The default, and smallest possible value, is 128 MB.
I have lowered the recommended maximum supported points based on testing. I have added a note suggesting an increase in Lambda memory and troubleshooting ingesting large batches.

2025-03-29 01:01 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/line_protocol_parser.rs
> +    }
All records are now ingested with common attributes. The common attributes are measure name, dimensions, timestamp precision, and measure value type.

2025-03-29 01:02 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/records_builder.rs
> +    }
`OnceCell` is now used for environment variables. `lib.rs` and `timestream_utils.rs` have their own environment variable configuration, to support adding more parsers and ingestors in the future that don't need the Timestream environment variables to be set.

2025-03-29 01:03 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +                        .await;
A `HashSet` is now used to track previously created tables. The `retry_with_backoff` function also checks for conflict exceptions, so that different invocations don't erroneously try to create existing tables.

2025-03-29 01:05 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +    }
All messages for errors now include what operation was being attempted (such as record ingestion or table creation) and whether the error is retryable. For AWS SDK for Rust errors, I added the function `is_retryable_status_code` to check the status code of errors.

2025-03-29 01:05 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +            thread::sleep(time::Duration::from_secs(TIMESTREAM_API_WAIT_SECONDS));
I have added the function `retry_with_backoff` which uses jitters. This function can be used with any kind of request.

2025-03-29 01:06 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/lib.rs
> +                        .await;
Added.

2025-03-29 01:06 UTC, trevorbonas commented on integrations/influxdb_connector/influxdb-timestream-connector/src/timestream_utils.rs
> +            info!("SdkError: {:?}", error.raw_response().unwrap());
Changed.

2025-04-01 22:20 UTC, pdhamoth approved these changes
lgtm. thanks

2025-04-15 19:26 UTC, merged